CREATE TABLE REGION (
    R_REGIONKEY INTEGER,
    R_NAME CHAR(25),
    R_COMMENT VARCHAR(152)
);

CREATE TABLE NATION (
    N_NATIONKEY INTEGER,
    N_NAME CHAR(25),
    N_REGIONKEY INTEGER,
    N_COMMENT VARCHAR(152)
);

CREATE TABLE SUPPLIER (
    S_SUPPKEY INTEGER,
    S_NAME CHAR(25),
    S_ADDRESS VARCHAR(40),
    S_NATIONKEY INTEGER,
    S_PHONE CHAR(15),
    S_ACCTBAL DOUBLE,
    S_COMMENT VARCHAR(101)
);

CREATE TABLE CUSTOMER (
    C_CUSTKEY INTEGER,
    C_NAME VARCHAR(25),
    C_ADDRESS VARCHAR(40),
    C_NATIONKEY INTEGER,
    C_PHONE CHAR(15),
    C_ACCTBAL DOUBLE,
    C_MKTSEGMENT CHAR(10),
    C_COMMENT VARCHAR(117)
);

CREATE TABLE PART (
    P_PARTKEY INTEGER,
    P_NAME VARCHAR(55),
    P_MFGR CHAR(25),
    P_BRAND CHAR(10),
    P_TYPE VARCHAR(25),
    P_SIZE INTEGER,
    P_CONTAINER CHAR(10),
    P_RETAILPRICE DOUBLE,
    P_COMMENT VARCHAR(23)
);

CREATE TABLE PARTSUPP (
    PS_PARTKEY INTEGER,
    PS_SUPPKEY INTEGER,
    PS_AVAILQTY INTEGER,
    PS_SUPPLYCOST DOUBLE,
    PS_COMMENT VARCHAR(199)
);

CREATE TABLE ORDERS (
    O_ORDERKEY INTEGER,
    O_CUSTKEY INTEGER,
    O_ORDERSTATUS CHAR(1),
    O_TOTALPRICE DOUBLE,
    O_ORDERDATE DATE,
    O_ORDERPRIORITY CHAR(15),
    O_CLERK CHAR(15),
    O_SHIPPRIORITY INTEGER,
    O_COMMENT VARCHAR(79)
);

CREATE TABLE LINEITEM (
    L_ORDERKEY INTEGER,
    L_PARTKEY INTEGER,
    L_SUPPKEY INTEGER,
    L_LINENUMBER INTEGER,
    L_QUANTITY DOUBLE,
    L_EXTENDEDPRICE DOUBLE,
    L_DISCOUNT DOUBLE,
    L_TAX DOUBLE,
    L_RETURNFLAG CHAR(1),
    L_LINESTATUS CHAR(1),
    L_SHIPDATE DATE,
    L_COMMITDATE DATE,
    L_RECEIPTDATE DATE,
    L_SHIPINSTRUCT CHAR(25),
    L_SHIPMODE CHAR(10),
    L_COMMENT VARCHAR(44)
);
