ALTER TABLE REGION ADD CONSTRAINT R_PK_REGIONKEY PRIMARY KEY (R_REGIONKEY);
ALTER TABLE NATION ADD CONSTRAINT N_PK_NATIONKEY PRIMARY KEY (N_NATIONKEY);
ALTER TABLE SUPPLIER ADD CONSTRAINT S_PK_SUPPKEY PRIMARY KEY (S_SUPPKEY);
ALTER TABLE CUSTOMER ADD CONSTRAINT C_PK_CUSTKEY PRIMARY KEY (C_CUSTKEY);
ALTER TABLE PART ADD CONSTRAINT P_PK_PARTKEY PRIMARY KEY (P_PARTKEY);
ALTER TABLE PARTSUPP ADD CONSTRAINT PS_PK_PARTKEY_SUPPKEY PRIMARY KEY (PS_PARTKEY, PS_SUPPKEY);
ALTER TABLE ORDERS ADD CONSTRAINT O_PK_ORDERKEY PRIMARY KEY (O_ORDERKEY);
ALTER TABLE LINEITEM ADD CONSTRAINT L_PK_ORDERKEY_LINENUMBER PRIMARY KEY (L_ORDERKEY, L_LINENUMBER);

CREATE INDEX N_FK_REGIONKEY ON NATION (N_REGIONKEY);
CREATE INDEX N_IDX_NAME ON NATION (N_NAME);
CREATE INDEX S_FK_NATIONKEY ON SUPPLIER (S_NATIONKEY);
CREATE INDEX C_FK_NATIONKEY ON CUSTOMER (C_NATIONKEY);
CREATE INDEX C_IDX_ACCTBAL ON CUSTOMER (C_ACCTBAL);
CREATE INDEX C_IDX_MKTSEGMENT ON CUSTOMER (C_MKTSEGMENT);

CREATE INDEX P_IDX_SIZE ON PART (P_SIZE);
CREATE INDEX P_IDX_TYPE ON PART (P_TYPE);
CREATE INDEX P_IDX_BRAND ON PART (P_BRAND);
CREATE INDEX P_IDX_CONTAINER ON PART (P_CONTAINER);
CREATE INDEX P_COMP_SIZE_BRAND_TYPE ON PART (P_SIZE, P_BRAND, P_TYPE);

CREATE INDEX PS_FK_PARTKEY ON PARTSUPP (PS_PARTKEY);
CREATE INDEX PS_FK_SUPPKEY ON PARTSUPP (PS_SUPPKEY);
CREATE INDEX PS_IDX_SUPPLYCOST ON PARTSUPP (PS_SUPPLYCOST);
CREATE INDEX O_FK_CUSTKEY ON ORDERS (O_CUSTKEY);
CREATE INDEX O_IDX_ORDERDATE ON ORDERS (O_ORDERDATE);
CREATE INDEX L_FK_ORDERKEY ON LINEITEM (L_ORDERKEY);
CREATE INDEX L_FK_PARTKEY ON LINEITEM (L_PARTKEY);
CREATE INDEX L_FK_SUPPKEY ON LINEITEM (L_SUPPKEY);
CREATE INDEX L_IDX_QUANTITY ON LINEITEM (L_QUANTITY);
CREATE INDEX L_IDX_SHIPDATE ON LINEITEM (L_SHIPDATE);
CREATE INDEX L_IDX_RECEIPTDATE ON LINEITEM (L_RECEIPTDATE);
CREATE INDEX L_COMP_PARTKEY_SUPPKEY ON LINEITEM (L_PARTKEY, L_SUPPKEY);
